### PR TITLE
Add arm64 support to CMake build

### PR DESCRIPTION
**Pull request by neonichu**
This is pretty speculative, I just copied the `SwiftSupport.cmake` from swift-argument-parser which seems to have support for arm64.

### CODE REVIEW

**Comment by neonichu** [comment]
Testing this out first via cross-repo testing on a Swift PR.

**Comment by tomerd** [comment]
cc @lorentey @compnerd @shahmishal 

if this works I think we would also need a new tag and update swift build script to pull it

**Comment by tomerd** [comment]
@neonichu @lorentey @compnerd we need this (+ new tag) to unblock https://github.com/apple/swift-package-manager/pull/3632. do you think this is ready?

**Comment by lorentey** [comment]
I'm ready to hit the merge button & tag a release if y'all say it works as expected.

@swift-ci test

**Comment by compnerd** [comment]
I think that this is slightly regressing the behavior.  I think that there are now out of sync (foundation, dispatch, etc have a copy as well).  The install layout has evolved a bit from the 5.1/5.2 days.  All the platforms now support the directory layout as well.  Windows prefers that layout with the module being triple named rather than just arch I believe.

**Comment by neonichu** [comment]
@compnerd Do you have a suggestion on which version of this file we should standardize?

**Comment by compnerd** [comment]
The changes that I believe haven't been synced are the ones to `_install_target` here:
https://github.com/compnerd/swift-win32/blob/main/cmake/Modules/SwiftSupport.cmake#L53-L92

The changes that you have to the `get_swift_host_arch` we can get away with as we do not expect someone to define `CMAKE_OSX_DEPLOYMENT_TARGET` on non-Darwin targets, but this seems somewhat fragile.  I think that this might be a better check:

```cmake
elseif ("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "AArch64|ARM64")
  if(CMAKE_SYSTEM_NAME MATCHES Darwin)
    set("${result_var_name}" "arm64" PARENT_SCOPE)
  else()
    set("${result_var_name}" "aarch64" PARENT_SCOPE)
  endif()
```

**Comment by neonichu** [comment]
OK, thanks. I updated it, but it seems like we do need the lowercase "arm64" in the check of `CMAKE_SYSTEM_PROCESSOR`, otherwise this doesn't work on my M1 machine.

**Comment by compnerd** [comment]
Hmm, I wonder if we should do `string(TOUPPER` or `string(TOLOWER` to make sure that we do the case insensitive match.  That is rather annoying, but we shouldn't be gating this on that.

**Comment by compnerd** [comment]
I think that you missed the update for the second half of the change (the install location).

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
OK, I removed the unnecessary changes and tested this locally, seems to work fine.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
LGTM; we should verify that the Linux ARM64 builds are unimpacted, but otherwise, LGTM

**Comment by neonichu** [comment]
Actually, I think I flipped it with my last edits, it'll now use "aarch64" on Darwin.

**Comment by tomerd** [comment]
@compnerd @lorentey how are we feeling about this?

**Comment by lorentey** [comment]
I'm happy to merge & tag as soon as someone confirms this is what we want. 😉 

@neonichu, did you mean to swap the spellings? IIUC Swift Argument Parser uses `arm64` on Darwin, and `aarch64` elsewhere.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@lorentey Yes, absolutely. I failed to push my latest changes. Interestingly, it seemed to have no impact on being able to build, either version worked.

**Comment by tomerd** [comment]
@lorentey I guess we need a new tag, so we can pull this into toolchain + SwiftPM. Do you have any other pending changes?

**Pull request merged**
