### PR TITLE
[OrderedCollections] Update docs to state that the sort algorithm is stable

### LINKED ISSUE #186: [OrderedCollections] Document Sorting as Stable
There are three pairs of `sort(by:)` and `sort()` methods, documented with:

> The sorting algorithm is not guaranteed to be stable.

- `OrderedDictionary.Elements.sort(by:)`
- `OrderedDictionary.Elements.sort()`
- `OrderedDictionary.sort(by:)`
- `OrderedDictionary.sort()`
- `OrderedSet.sort(by:)`
- `OrderedSet.sort()`

Should these APIs be documented like the [SE-0372][] implementation?

[SE-0372]: <https://github.com/apple/swift-evolution/blob/main/proposals/0372-document-sorting-as-stable.md>

### PR DESCRIPTION
**Pull request by lorentey**
Resolves #186.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [X] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by benrimmington** [comment]
Should the three `sort(by:)` comments still refer to the `areInIncreasingOrder` parameter?

https://github.com/apple/swift/blob/5d832bf946bef47a1a7e894ca32b9768799f1863/stdlib/public/core/Sort.swift#L234-L236

**Comment by lorentey** [comment]
Oops, you're absolutely right, I mistakenly lost the custom wording for the closure-taking variants. Restored!

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
