### PR TITLE
Stop depending on swift-collections-benchmark

### PR DESCRIPTION
**Pull request by lorentey**
Instead, move the benchmark suite into its own private nested package, under `Benchmarks/`.

The recommended way to build & run benchmarks is via the `Utils/run-benchmarks.sh` script, which continues to work as before with this change.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [ ] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
This will also need to be cherry-picked on the release/1.0 branch.

**Comment by tomerd** [comment]
looks great.

is checking-in the resolved file intentional?

**Comment by tomerd** [comment]
cc @neonichu @abertelrud

**Comment by lorentey** [comment]
> is checking-in the resolved file intentional?

It is! I'd prefer if we ran the benchmarks using a consistent codebase, in as much as that's possible. (Not that I'd expect picking up a new argument parser would directly affect measurements -- but subtle function alignment changes within the CollectionsBenchmark module (such as when picking up a new version of a dependency) can measurably perturb benchmarks. The runner script tries to align modules on page boundaries, but this doesn't help if a function gets slightly offset within the module.)

(If this proves unnecessary, and/or having to manually update dependencies becomes too much of a chore, then we can always remove the lock later.)

**Comment by lorentey** [comment]
There is no point in having the top-level resolved file though; I'll remove it.

**Comment by lorentey** [comment]
@swift-ci test

**Review by abertelrud — APPROVED** [review]
Thanks!  This is much nicer for clients, I think.

**Pull request merged**
