### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by compnerd**
Remove missing file.  Thanks to @stevenbrix for identifying this!

### CODE REVIEW

**Review by lorentey — APPROVED** [review]

**Comment by lorentey** [comment]
Hm, this needs to go on release/1.1 too. I'll cherry-pick it.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@stevenbrix Incidentally, how did you discover this? (I hope y'all aren't using unreleased commits from `main` in production -- this repository really isn't really suitable for such use yet, as PR testing isn't nearly strong enough to catch obvious mistakes, and manual test runs only occur once in a blue moon.)

**Comment by stevenbrix** [comment]
@lorenty no not using it in production, I was playing around with building the swift on windows tool chain

**Comment by lorentey** [comment]
Ah, so it sounds like toolchain builds might be picking up the `main` branch of this package, rather than a stable release tag. That is not great -- the toolchain would probably be better of using a specific stable version, even in development builds. 

This isn't a huge problem, but it might unnecessary increase our work load with these sorts of trivial-but-not-caught-by-PR-testing issues. I'll make a note to look into it.

**Pull request merged**
