### PR TITLE
Documentation: remove invalid file characters

### PR DESCRIPTION
**Pull request by compnerd**
`:` is not supported on Windows as a valid file name character.  Replace
the `:` with `-`.

Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.

### Checklist
- [ ] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [ ] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [ ] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by lorentey — APPROVED** [review]
👍

**Comment by lorentey** [comment]
@swift-ci test

**Comment by compnerd** [comment]
@lorentey - mind merging this change?  It actually prevents even cloning the repository on Windows.

**Pull request merged**
