### PR TITLE
Replace Index with Int where possible

### LINKED ISSUE #30: OrderedSet append does not return the same type as insert
The API for insert in an `OrderedSet` is
```swift
public mutating func insert(_ item: Element, at index: Index) -> (inserted: Bool, index: Index)
```

and the one for append is
```swift
public mutating func append(_ item: Element) -> (inserted: Bool, index: Int)
```

I understand the return types are technically the same because `Index` is `Int`, always, but from a semantic point of view, shouldn’t the append method return a `(inserted: Bool, index: Index)` tuple?

### Information

- **Package version:** Swift Collection `0.0.2`
- **Platform version:** macOS `11.3`
- **Swift version:**
```text
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.4.0
```

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
N/A

### Expected behavior
`OrderedSet`’s `append` method to return `(inserted: Bool, index: Index)`.

### Actual behavior
It returns `(inserted: Bool, index: Int)`.

### PR DESCRIPTION
**Pull request by Frizlab**
Closes #30. I tried to find all instances of Int where Index should have been used in the Source. I did not search the tests because the issue is semantic only, and my changes only have impact on the public API.

### Checklist
- [x] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [x] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [x] I've followed the coding style of the rest of the project.
- [x] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [x] I've added benchmarks covering new functionality (if appropriate).
- [x] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by xwu** [comment]
Mmm, I'm not certain that the benefits outweigh the drawbacks here with this change. `Index` is explicitly an associated type, and it's arguable that readers _want_ to know what the actual associated type is. Personally I prefer the status quo.

**Comment by Frizlab** [comment]
@xwu In any case the public API is inconsistent now (`Index` and `Int` are both used; see #30 for an example). I do think one of both should be chosen ;-)

Reading the source code of Swift’s `Array`, it seems `Int` is used, not `Index`, so maybe using `Int` would indeed be better for consistency with Swift itself.

I personally slightly prefer `Index` over `Int`, but I’d happy to update this PR to use `Int` instead of `Index` if the maintainers think it’s best.

**Comment by lorentey** [comment]
The use of `Index` is mostly a leftover from the initial implementations where these collections used custom index types. 

I'd prefer if we went the other way and used `Int` everywhere -- the fact that these have integer indices carry additional semantic meaning, and it makes sense not to hide this information behind a typealias.

**Comment by Frizlab** [comment]
Done

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
