### PR TITLE
Update OrderedDictionary/OrderedSet documentation

### PR DESCRIPTION
**Pull request by hassila**
Update documentation to reflect that all bits used in the hashing needs to be part of the equality check for correctness (not strictly necessarily vice-versa as the current documentation reads). 

See also:

https://github.com/apple/swift/issues/66282#issuecomment-1572642416

### Checklist
- [x] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [x] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [ ] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by xwu** [comment]
@hassila, the documentation is correct as-is but perhaps is easy to misread. The text you're proposing to edit isn't about _correctness_: it's in a section about _performance_ (literally, the subsection is titled "Performance").

As the preceding paragraph states, if all values of a type have the same hash despite being unequal, it's not a correctness issue but it _is_ a performance issue. Therefore, the paragraph that follows says that the _easiest_ (not _only_) correct way to achieve good performance is to follow best practices that include hashing everything that is compared in `==`. This helps the hasher to prevent repeatable hash collisions.

**Comment by hassila** [comment]
Thanks @xwu, I did indeed misread the context and had recently read the discussion in the comment in the swift case I linked to in the description where they looked at this distinction in the standard library - now, there is obviously zero harm (and usually best practice) to include all bits in both the hashing and equality operations, but I thought it might makes sense to turn around the statement made so it still recommend this but also addresses the correctness (with no harm). 

If you disagree I'll just close this.

**Comment by xwu** [comment]
Changing the statement as you propose, though, wouldn't give the correct advice about what one needs to do in order for the hasher to avoid collisions in order to maintain performance.

**Comment by lorentey** [comment]
> now, there is obviously zero harm (and usually best practice) to include all bits in both the hashing and equality operations

This is an understatement. Doing this is not only _not_ harmful, but it is the only way to ensure that the documented performance promises of Set/Dictionary actually hold true.

A type that hashes less information than what it compares in `==` is, in almost all cases, an open invitation to reliability attacks.

(I added a similar note in the referenced issue, too. I'm a bit miffed that HashDoS vulnerabilities are still widely ignored/dismissed; hashing can be tricky enough without deliberately breaking it! 😛)

**Pull request closed without merging**
