### PR TITLE
Integrate PriorityQueueModule, BitCollections, PersistentCollections, SortedCollections into release/1.1

### PR DESCRIPTION
**Pull request by lorentey**
Open a release/1.1 branch to simplify ongoing work on the new collection types.

This provisionally includes modules that aren't ready to land yet, and it includes preliminary API that hasn't gone through any sort of formal API review.

Things may be rapidly changing on this branch, and we may need to end up taking out parts that can't fit into the converged 1.1 release. This code is _extremely_ not ready for any production use.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
This includes and is building on top of the excellent work of @AquaGeek, @MahanazAtiqullah, @msteindorfer, @vihanb, and lots of others.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test

**Comment by msteindorfer** [comment]
Thanks @lorentey.

It appears that the README needs to be updated to reflect the changes of the merged features targeted for `release/1.1`.

**Pull request merged**
