### PR TITLE
add support for riscv64

### PR DESCRIPTION
**Pull request by futurejones**
Add support for `riscv64` as host architecture.

### Checklist
- [x] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [x] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [x] I've followed the coding style of the rest of the project.
- [x] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [x] I've added benchmarks covering new functionality (if appropriate).
- [x] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by futurejones** [comment]
@lorentey any progress?

**Review by lorentey — APPROVED** [review]
Sure! 

The caveat is that we cannot guarantee that the code will continue to work as is on this architecture -- we don't have CI set up for RISC-V, nor capacity to manually run tests on it.

**Comment by lorentey** [comment]
Did you intentionally target this PR on the `main` branch, rather than on the `release/1.1` series?

**Comment by lorentey** [comment]
Yes. Changes in this repository need to land in the earliest release branch that wants to ship them. 

The project maintainer then merges (not cherry-picks, merges) them to downstream branches as needed.

This is explained in the [README](https://github.com/apple/swift-collections?tab=readme-ov-file#branching-strategy).

**Comment by futurejones** [comment]
@lorentey, apologies,  I should have read the README more closely.
Yes this should be targeting the `release/1.1` branch.
Can you make this change.
Thanks.

**Comment by lorentey** [comment]
@futurejones Do you no longer need this change, or were you just unable to retarget it on the release/1.1 branch?

**Comment by futurejones** [comment]
@lorentey I don't have write access to this repository so I can't edit and retarget the PR target branch. 
That is why I asked you to make the change

> **Yes this should be targeting the release/1.1 branch.
Can you make this change.
Thanks.**

After waiting for nearly 2 months with no response I decided to close the PR rather get stuck in a frustrating cycle of pinging and getting no response. 

This is what I have been experiencing with other PR's that I have been trying to get approved in several other swift sub projects.

Whether or not this PR gets approved and merged is not for my need or benefit, it was to improve the swift project support for everyone.

anyway, thanks for responding.

**Comment by lorentey** [comment]
@futurejones I see. I can rebase your commit on top of release/1.1 for you if you want. I have no way to verify that the result will works though, and I strongly suspect the CMake change is not going to be enough.

The swift-collections codebase includes a handful of cases where Swift code is conditional on the target architecture, and none of those know about `riscv64` as a possibility. To properly support 64-bit RISC-V, I expect these will need to be updated, preferably by refactoring them to use the new `_pointerBitWidth` condition (we generally have these because we needed to know the size of pointers).

**Pull request closed without merging**
