### PR TITLE
Update TreeSet.md

### PR DESCRIPTION
**Pull request by hassila**
Fix typo

Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.

### Checklist
- [ x] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [ x] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [ x] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [x ] I've updated the documentation if necessary.

### CODE REVIEW

**Review by lorentey — APPROVED** [review]
Good catch! 👍 

I think this should better go on `release/1.1`, not `main`; would you be willing to rebase this PR on that branch? (Otherwise this change would only show up in the feature release following 1.1.)

**Comment by hassila** [comment]
Sure, I opened https://github.com/apple/swift-collections/pull/297 for that, will close this one.

**Comment by MaxDesiatov** [comment]
Does cherry-picking from `release/1.1` to `main` happen after the fact? If not, should this be reopened and still considered for `main`?

**Comment by lorentey** [comment]
I'm manually propagating changes along the `release/1.0` → `release/1.1` → `main` chain, so things landing for 1.1 will (eventually) also appear on `main` -- there is no need to file separate PRs for each branch.

This should probably be explained in the README; I'll make a note to update it.

**Pull request closed without merging**
