### PR TITLE
Support Windows ARM64 builds.

### PR DESCRIPTION
**Pull request by hjyamauchi**
Handle the "ARM64" system processor type.

### Checklist
- [y] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [y] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [y] I've followed the coding style of the rest of the project.
- [n] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [n] I've added benchmarks covering new functionality (if appropriate).
- [n] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [n] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by hjyamauchi** [comment]
@compnerd

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by hjyamauchi** [comment]
@compnerd Can this be merged?

**Comment by compnerd** [comment]
Yeah, I suppose that this should also go into release/1.1. I hope not too many more - Windows, Darwin: ARM64; Linux: aarch64. The case insensitivity is annoying, but c'est la vie.

**Comment by lorentey** [comment]
It turns out we already have this change on `main`, `release/1.1` and `release/1.0`! -- GitHub didn't flag the PR as invalid because it duplicates a previous change exactly, so it can technically be merged without any conflicts. 😮

The root of the issue is the swift's release/5.10 branch is picking up an obsolete tag of this package. (The [PR that updated the branch specs](https://github.com/apple/swift/pull/69714) only landed on swift's main branch, [not release/5.10](https://github.com/apple/swift/pull/69737).) We may be too late to retry landing that for 5.10.0, but perhaps it could be possible to do it in a 5.10.1 update.

What a mess!

**Pull request closed without merging**
