### PR TITLE
Add the @discardableResult attribute to OrderedSet.insert(_:at:)

### LINKED ISSUE #19: OrderedSet.insert should be @discardableResult
Often I just need to insert an element into the OrderedSet. For now I need to prefix that with '_ = ' which in my option should be avoided. Please consider adding @discardableResult to 

insert(_ item: Element, at index: Index) -> (inserted: Bool, index: Index)

Best, Felix

### PR DESCRIPTION
**Pull request by kielgillard**
Fixes #19.

It does not seem appropriate to write a test for this change. However, I am open to other points of view and will gladly own further work.

### Checklist
- [x] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [x] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [x] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [x] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Review by lorentey — APPROVED** [review]
This looks good, thank you!

It would be useful to see if there any other APIs in the package that are currently missing this attribute -- if we missed one, we may have missed others.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by kielgillard** [comment]
I did wonder if the following functions should have this attribute, too:
`updateOrAppend(_ item: Element) -> Element?`
`updateOrInsert(_ item: Element, at index: Index) -> (originalMember: Element?, index: Index)`

**Comment by lorentey** [comment]
@kielgillard I think so, if only by analogue to `SetAlgebra`'s `update(with:)` requirement. Can you add those to this PR? 😊

(I wonder how often these would be used without looking at the return value, but there is nothing wrong with discarding it, either -- and I don't think we want to force people to do the `_ = foo.updateOrAppend(...)` dance to achieve that.)

**Comment by kielgillard** [comment]
@swift-ci test

**Comment by kielgillard** [comment]
@lorentey done.

My intuition is people will probably be using these "update or" APIs specifically for the return value but, like you said, there's no need for the API to be a jerk about it in case you don't want it!

**Comment by lorentey** [comment]
Looks good, thanks! 👍 

@swift-ci test

**Pull request merged**
