### PR TITLE
[CMake] Add support for WebAssembly target architectures

### PR DESCRIPTION
**Pull request by kateinoigakukun**
To repair the swift-corelibs-foundation build on WebAssembly, we need to add support for Wasm targets to swift-collections' CMake build system.

### Checklist
- [x] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [x] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [x] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [x] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Review by lorentey — COMMENTED** [review]
Looks good! Did you mean this to target the `main` branch instead of `release/1.1`?

**Comment by kateinoigakukun** [comment]
@lorentey You are right, this should target `release/1.1`. Thanks!

**Comment by lorentey** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
@swift-ci test macOS

**Comment by kateinoigakukun** [comment]
Hi @lorentey, do we have any chance to release a new 1.1.x tag including this change? We need this change to repair Foundation build on Wasm. Thanks in advance :pray:

**Pull request merged**
