### PR TITLE
[CMake] swift-collections → SwiftCollections

### PR DESCRIPTION
**Pull request by lorentey**
This is an integration FIXME for SwiftPM: https://github.com/apple/swift-package-manager/pull/3595#issuecomment-875201764

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [ ] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
Cc @compnerd @tomerd

**Comment by lorentey** [comment]
@swift-ci test

**Comment by tomerd** [comment]
lgtm, I think @compnerd also wanted to fix some path issue https://github.com/apple/swift-package-manager/pull/3595/files#diff-fdc89d912e967e4b700e1bb41e08552bb416b5c5551bbae5b1ccac134db6c3e5R608 (should emit into "cmake/modules")

**Comment by lorentey** [comment]
> lgtm, I think @compnerd also wanted to fix some path issue https://github.com/apple/swift-package-manager/pull/3595/files#diff-fdc89d912e967e4b700e1bb41e08552bb416b5c5551bbae5b1ccac134db6c3e5R608 (should emit into "cmake/modules")

Ah, that makes sense -- I was just wondering about that very line.

**Review by compnerd — CHANGES_REQUESTED** [review]
L36 also needs to be altered to be `SwiftCollectionsConfig.cmake` to match the `SwifCollections`.  At the same time, simply changing that path to `cmake/modules/SwiftCollectionsConfig.cmake` should fix the location as well.  I can run a test with the updates for the CMake build on azure.

**Comment by lorentey** [comment]
@compnerd I applied that change and moved this `export()` under cmake/modules for symmetry with the other packages.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by tomerd** [comment]
@lorentey I can test this once merged and before you tag

**Comment by tomerd** [comment]
@lorentey confirmed this works, feel free to tag

**Pull request merged**
